version: "3.3"

services:
  bot:
    container_name: "${BOT_CONTAINER_NAME}"
    build:
      context: .
      dockerfile: Dockerfile
    working_dir: "/usr/src/app/${BOT_NAME}"
    volumes:
      - .:/usr/src/app/${BOT_NAME}
    command: python3 -m bot
    restart: unless-stopped
    env_file:
      - ".env"
    depends_on:
      - db
  db:
    image: postgres:latest
    container_name: "keywords_DB"
    volumes:
      - ./data:/var/lib/postgresql/data/
    ports:
      - "${DATABASE_PORT}:5432"
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${DATABASE_NAME}
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
